flaskshop/dashboard/__init__.py
from . import views
#TODO: mail_send, mail_compose, change_user_right,

flaskshop/dashboard/views.py
from functools import wraps
from flask import Blueprint, render_template, abort, redirect, url_for
from flask_login import login_required, current_user

from flaskshop.account.models import User, UserAddress
from flaskshop.public.models import MenuItem

from .models import DashboardMenu
from .forms import DashboardMenuForm

blueprint = Blueprint("dashboard", __name__, url_prefix="/dashboard")


@blueprint.context_processor
def inject_param():
    menus = DashboardMenu.first_level_items()
    return {"menus": menus}


def admin_required(func):
    @wraps(func)
    def decorated_view(*args, **kwargs):
        if not current_user.is_admin:
            abort(401)
        return func(*args, **kwargs)

    return decorated_view


@blueprint.before_request
@admin_required
@login_required
def before_request():
    """The whole blueprint need to login first"""
    pass


@blueprint.route("/")
def index():
    return render_template("dashboard/index.html")


@blueprint.route("/list")
def list():
    return render_template("dashboard/list.html")


@blueprint.route("/users")
def users():
    users = User.query.all()
    props = {
        "id": "ID",
        "username": "Username",
        "email": "Email",
        "active": "Is Active",
        "is_admin": "Is Admin",
    }
    context = {}
    return render_template("dashboard/list.html", props=props, items=users)


@blueprint.route("/menus")
def menus():
    menus = MenuItem.query.all()
    props = {
        "id": "ID",
        "title": "Title",
        "order": "Order",
        "site_id": "Site Id",
        "parent_id": "Parent Id",
    }
    context = {
        "title": "Site Menus",
        "create_endpoint": "dashboard.dashboard_menus_create",
        "edit_endpoint": "dashboard.dashboard_menus_edit",
        "items": menus,
        "props": props,
    }
    return render_template("dashboard/list.html", **context)


@blueprint.route("/dashboard_menus")
def dashboard_menus():
    dashboard_menus = DashboardMenu.query.all()
    props = {
        "id": "ID",
        "title": "Title",
        "order": "Order",
        "endpoint": "Endpoint",
        "icon_cls": "Icon class",
        "parent_id": "Parent Id",
    }
    context = {
        "title": "Dashboard Menus",
        "create_endpoint": "dashboard.dashboard_menus_create",
        "edit_endpoint": "dashboard.dashboard_menus_edit",
        "items": dashboard_menus,
        "props": props,
    }
    return render_template("dashboard/list.html", **context)


@blueprint.route("/dashboard_menus/create", methods=["GET", "POST"])
def dashboard_menus_create():
    form = DashboardMenuForm()
    if form.validate_on_submit():
        menu = DashboardMenu()
        form.populate_obj(menu)
        menu.save()
        return redirect(url_for("dashboard.dashboard_menus"))
    parents = DashboardMenu.first_level_items()
    return render_template("dashboard/dashboard_menu.html", form=form, parents=parents)


@blueprint.route("/dashboard_menus/<menu_id>/edit", methods=["GET", "POST"])
def dashboard_menus_edit(menu_id):
    menu = DashboardMenu.get_by_id(menu_id)
    form = DashboardMenuForm(obj=menu)
    if form.validate_on_submit():
        form.populate_obj(menu)
        menu.save()
        return redirect(url_for("dashboard.dashboard_menus"))
    parents = DashboardMenu.first_level_items()
    return render_template("dashboard/dashboard_menu.html", form=form, parents=parents)

flaskshop/dashboard/views/__init__.py
from . import bp

flaskshop/dashboard/views/bp.py
from datetime import datetime
from flask import Blueprint, render_template
from flask_login import login_required
from pluggy import HookimplMarker
from sqlalchemy import func
from flask_babel import lazy_gettext

from flaskshop.extensions import db
from flaskshop.dashboard.models import DashboardMenu
from flaskshop.order.models import Order, OrderLine, OrderEvent
from flaskshop.product.models import Product
from flaskshop.account.models import User
from flaskshop.account.utils import permission_required
from flaskshop.settings import Config
from flaskshop.constant import Permission, OrderStatusKinds, OrderEvents
# from .mail import mails

from .user import users, user, user_edit, address_edit
from .site import (
    shipping_methods,
    shipping_methods_manage,
    site_menus,
    site_menus_manage,
    dashboard_menus,
    dashboard_menus_manage,
    site_pages,
    site_pages_manage,
    site_setting,
    plugin_list,
    plugin_enable,
    plugin_disable,
    config_index,
)
from .product import (
    attributes,
    attributes_manage,
    collections,
    collections_manage,
    categories,
    categories_manage,
    product_types,
    product_types_manage,
    products,
    product_detail,
    product_edit,
    product_create_step1,
    product_create_step2,
    variant_manage,
)
from .order import orders, order_detail, send_order, draft_order
from .discount import vouchers, vouchers_manage, sales, sales_manage

impl = HookimplMarker("flaskshop")


def index():
    def get_today_num(model):
        target = db.cast(datetime.now(), db.DATE)
        which = db.cast(model.created_at, db.DATE)
        return model.query.filter(which == target).count()

    def get_order_status(status):
        return {
            "count": Order.query.filter_by(status=status).count(),
            "kind": status,
        }

    onsale_products_count = Product.query.filter_by(on_sale=True).count()

    hot_product_ids = (
        db.session.query(OrderLine.product_id, func.count(OrderLine.product_id))
        .group_by(OrderLine.product_id)
        .order_by(func.count(OrderLine.product_id).desc())
        .all()
    )
    top5_products = []
    for product_id, order_count in hot_product_ids[:5]:
        p = Product.get_by_id(product_id)
        p.order_count = order_count
        top5_products.append(p)

    activity = OrderEvent.query.order_by(OrderEvent.id.desc()).limit(10)

    context = {
        "orders_total": Order.query.count(),
        "orders_today": get_today_num(Order),
        "users_total": User.query.count(),
        "users_today": get_today_num(User),
        "order_unfulfill": get_order_status(OrderStatusKinds.unfulfilled.value),
        "order_fulfill": get_order_status(OrderStatusKinds.fulfilled.value),
        "onsale_products_count": onsale_products_count,
        "top_products": top5_products,
        "activity": activity,
        "order_events": OrderEvents,
    }
    return render_template("index.html", **context)


@impl
def flaskshop_load_blueprints(app):
    bp = Blueprint(
        "dashboard", __name__, template_folder=Config.DASHBOARD_TEMPLATE_FOLDER
    )

    @bp.context_processor
    def inject_param():
        menus = DashboardMenu.first_level_items()
        return {"menus": menus}

    @bp.before_request
    @permission_required(Permission.EDITOR)
    @login_required
    def before_request():
        """The whole blueprint need to login first"""
        pass

    bp.add_url_rule("/", view_func=index)
    bp.add_url_rule("/site_menus", view_func=site_menus)
    bp.add_url_rule(
        "/site_menus/create", view_func=site_menus_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_menus/<id>/edit", view_func=site_menus_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/dashboard_menus", view_func=dashboard_menus)
    bp.add_url_rule(
        "/dashboard_menus/create",
        view_func=dashboard_menus_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/dashboard_menus/<id>/edit",
        view_func=dashboard_menus_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule("/site_pages", view_func=site_pages)
    bp.add_url_rule(
        "/site_pages/create", view_func=site_pages_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_pages/<id>/edit", view_func=site_pages_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/site_setting", view_func=site_setting, methods=["GET", "POST"])
    bp.add_url_rule("/plugin", view_func=plugin_list)
    bp.add_url_rule("/plugin/<id>/enable", view_func=plugin_enable, methods=["POST"])
    bp.add_url_rule("/plugin/<id>/disable", view_func=plugin_disable, methods=["POST"])
    bp.add_url_rule("/config", view_func=config_index)
    bp.add_url_rule("/users", view_func=users)
    bp.add_url_rule("/users/<user_id>", view_func=user)
    bp.add_url_rule(
        "/users/<user_id>/edit", view_func=user_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/users/address/<id>/edit", view_func=address_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule("/attributes", view_func=attributes)
    bp.add_url_rule(
        "/attributes/create", view_func=attributes_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/attributes/<id>/edit", view_func=attributes_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/collections", view_func=collections)
    bp.add_url_rule(
        "/collections/create", view_func=collections_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/collections/<id>/edit", view_func=collections_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/categories", view_func=categories)
    bp.add_url_rule(
        "/categories/create", view_func=categories_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/categories/<id>/edit", view_func=categories_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/product_types", view_func=product_types)
    bp.add_url_rule(
        "/product_types/create", view_func=product_types_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/product_types/<id>/edit",
        view_func=product_types_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule("/shipping_methods", view_func=shipping_methods)
    bp.add_url_rule(
        "/shipping_methods/create",
        view_func=shipping_methods_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/shipping_methods/<id>/edit",
        view_func=shipping_methods_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule("/products", view_func=products)
    bp.add_url_rule("/products/<id>", view_func=product_detail)
    bp.add_url_rule(
        "/products/create/step1",
        view_func=product_create_step1,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/products/create/step2",
        view_func=product_create_step2,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/products/<id>/edit", view_func=product_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/products/variant/create", view_func=variant_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/products/variant/<id>/edit", view_func=variant_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/orders", view_func=orders)
    bp.add_url_rule("/orders/<id>", view_func=order_detail)
    bp.add_url_rule("/orders/<id>/send", view_func=send_order)
    bp.add_url_rule("/orders/<id>/draft", view_func=draft_order)
    bp.add_url_rule("/vouchers", view_func=vouchers)
    bp.add_url_rule(
        "/vouchers/create", view_func=vouchers_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/vouchers/<id>/edit", view_func=vouchers_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule("/sales", view_func=sales)
    bp.add_url_rule("/sales/create", view_func=sales_manage, methods=["GET", "POST"])
    bp.add_url_rule("/sales/<id>/edit", view_func=sales_manage, methods=["GET", "POST"])
    # bp.add_url_rule("/mails", view_func=mails)# TODO: e-mail to user, create mail template, send promotion and product
    app.register_blueprint(bp, url_prefix="/dashboard")

flaskshop/dashboard/views/discount.py
from datetime import datetime

from flask import request, render_template, redirect, url_for

from flaskshop.discount.models import Voucher, Sale, SaleCategory, SaleProduct
from flaskshop.product.models import Product, Category
from flaskshop.dashboard.forms import VoucherForm, SaleForm
from flaskshop.constant import VoucherTypeKinds, DiscountValueTypeKinds
from flask_babel import lazy_gettext

def vouchers():
    page = request.args.get("page", type=int, default=1)
    pagination = Voucher.query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "type_human": lazy_gettext("Type"),
        "usage_limit": lazy_gettext("Usage Limit"),
        "used": lazy_gettext("Used"),
        "discount_value_type_human": lazy_gettext("Discount Type"),
        "discount_value": lazy_gettext("Discount Value"),
    }
    context = {
        "title": lazy_gettext("Voucher"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": lazy_gettext("vouchers"),
    }
    return render_template("list.html", **context)


def vouchers_manage(id=None):
    if id:
        voucher = Voucher.get_by_id(id)
        form = VoucherForm(obj=voucher)
    else:
        form = VoucherForm()
    if form.validate_on_submit():
        if not id:
            voucher = Voucher()
        start_date, end_date = form.validity_period.data.split("-")
        voucher.start_date = datetime.strptime(start_date.strip(), "%m/%d/%Y")
        voucher.end_date = datetime.strptime(end_date.strip(), "%m/%d/%Y")
        del form.validity_period
        form.populate_obj(voucher)
        voucher.save()
        return redirect(url_for("dashboard.vouchers"))
    products = Product.query.all()
    categories = Category.query.all()
    voucher_types = [dict(id=kind.value, title=kind.name) for kind in VoucherTypeKinds]
    discount_types = [
        dict(id=kind.value, title=kind.name) for kind in DiscountValueTypeKinds
    ]
    context = {
        "form": form,
        "products": products,
        "categories": categories,
        "voucher_types": voucher_types,
        "discount_types": discount_types,
    }
    return render_template("discount/voucher.html", **context)


def sales():
    page = request.args.get("page", type=int, default=1)
    pagination = Sale.query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "discount_value_type_label": lazy_gettext("Discount Type"),
        "discount_value": lazy_gettext("Discount Value"),
    }
    context = {
        "title": lazy_gettext("Sale"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": lazy_gettext("sales"),
    }
    return render_template("list.html", **context)


def sales_manage(id=None):
    if id:
        sale = Sale.get_by_id(id)
        form = SaleForm(obj=sale)
    else:
        form = SaleForm()
    if form.validate_on_submit():
        if not id:
            sale = Sale()
        sale.update_products(form.products.data)
        sale.update_categories(form.categories.data)
        del form.products
        del form.categories
        form.populate_obj(sale)
        sale.save()
        return redirect(url_for("dashboard.sales"))
    products = Product.query.all()
    categories = Category.query.all()
    discount_types = [
        dict(id=kind.value, title=kind.name) for kind in DiscountValueTypeKinds
    ]
    context = {
        "form": form,
        "products": products,
        "categories": categories,
        "discount_types": discount_types,
    }
    return render_template("discount/sale.html", **context)

flaskshop/dashboard/views/mail.py
from flask import render_template, redirect, url_for, request
from sqlalchemy import or_
from flask_babel import lazy_gettext

def mails():
    page = request.args.get("page", type=int, default=1)
    search_word = request.args.get("keyword")

flaskshop/dashboard/views/order.py
from datetime import datetime
from flask import request, render_template
from flask_babel import lazy_gettext

from flaskshop.order.models import Order
from flaskshop.constant import OrderStatusKinds


def orders():
    page = request.args.get("page", type=int, default=1)
    query = Order.query.order_by(Order.id.desc())

    status = request.args.get("status", type=int)
    if status:
        query = query.filter_by(status=status)
    order_no = request.args.get("order_number", type=str)
    if order_no:
        query = query.filter(Order.token.like(f"%{order_no}%"))
    created_at = request.args.get("created_at", type=str)
    if created_at:
        start_date, end_date = created_at.split("-")
        start_date = datetime.strptime(start_date.strip(), "%m/%d/%Y")
        end_date = datetime.strptime(end_date.strip(), "%m/%d/%Y")
        query = query.filter(Order.created_at.between(start_date, end_date))
    pagination = query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "identity": lazy_gettext("Identity"),
        "status_human": lazy_gettext("Status"),
        "total_human": lazy_gettext("Total"),
        "user": lazy_gettext("User"),
        "created_at": lazy_gettext("Created At"),
    }
    context = {
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "order_stats_kinds": OrderStatusKinds,
    }
    return render_template("order/list.html", **context)


def order_detail(id):
    order = Order.get_by_id(id)
    return render_template("order/detail.html", order=order)


def send_order(id):
    order = Order.get_by_id(id)
    order.delivered()
    return render_template("order/detail.html", order=order)


def draft_order(id):
    order = Order.get_by_id(id)
    order.draft()
    return render_template("order/detail.html", order=order)

flaskshop/order/__init__.py
from . import views

flaskshop/order/payment/__init__.py
from . import zhifubao

flaskshop/templates/dashboard/order/detail.html
{% import 'dashboard/_vendor.html' as vendor %}
{% extends 'dashboard/layout.html' %}
{% block body %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="invoice p-3 mb-3">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-12">
                            <h4>
                                <i class="fa fa-globe"></i> {{order.token}}
                                <small class="float-right">{% trans %}Created At{% endtrans %}: {{order.created_at}}</small>
                            </h4>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            <b>{% trans %}Status{% endtrans %}:</b> {{order.status_human}}<br>
                            <b>{% trans %}Payment Status{% endtrans %}:</b> {{order.payment.status_human}}<br>
                            <b>{% trans %}Payment Due{% endtrans %}:</b> {{order.payment.paid_at}}<br>
                            <b>{% trans %}Account{% endtrans %}:</b> {{order.user}}
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <strong>{% trans %}Shipping Address{% endtrans %}</strong>
                            <address>
                                {{order.shipping_address | safe}}
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            <strong>{% trans %}Shipping Method{% endtrans %}</strong>
                            <address>
                                {{order.shipping_method_name}} (${{order.shipping_price_net}})
                            </address>
                        </div>
                    </div>
                    <!-- /.row -->

                    <!-- Table row -->
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>{% trans %}Qty{% endtrans %}</th>
                                        <th>{% trans %}Product{% endtrans %}</th>
                                        <th>{% trans %}SKU{% endtrans %}</th>
                                        <th>{% trans %}Unit Price{% endtrans %}</th>
                                        <th>{% trans %}Subtotal){% endtrans %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.lines %}
                                    <tr>
                                        <td>{{item.quantity}}</td>
                                        <td>
                                            <a href="{{url_for('dashboard.product_detail', id=item.product_id)}}"
                                                target="_blank">
                                                {{item.product_name}}
                                            </a>
                                        </td>
                                        <td>{{item.product_sku}}</td>
                                        <td>${{item.unit_price_net}}</td>
                                        <td>${{item.quantity * item.unit_price_net}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <!-- accepted payments column -->
                        <div class="col-6">
                            <p class="lead">{% trans %}Payment Method{% endtrans %}: {{order.payment.payment_method}}</p>
                            <p class="lead">{% trans %}Order Note{% endtrans %}:</p>
                            <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                                {{order.note}}
                            </p>
                        </div>
                        <!-- /.col -->
                        <div class="col-6">
                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th style="width:50%">{% trans %}Subtotal{% endtrans %}:</th>
                                        <td>${{order.total_net}}</td>
                                    </tr>
                                    <tr>
                                        <th>{% trans %}Shipping{% endtrans %}:</th>
                                        <td>${{order.shipping_price_net}}</td>
                                    </tr>

                                    <tr>
                                        <th>{% trans %}Discount{% endtrans %}:</th>
                                        <td>-${{ order.discount_amount  }}({{ order.discount_name }})</td>
                                    </tr>

                                    <tr>
                                        <th>{% trans %}Total{% endtrans %}:</th>
                                        <td>${{order.total}}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    <div class="row no-print">
                        <div class="col-12">
                            {% if order.status_human == "fulfilled" %}
                            <a class="btn btn-success float-right"
                                href="{{url_for('dashboard.send_order', id=order.id)}}">
                                <i class="fa fa-credit-card"></i> {% trans %}Send Order{% endtrans %}
                            </a>
                            {% elif order.status_human == "unfulfilled" %}
                            <a class="btn btn-danger float-right"
                                href="{{url_for('dashboard.draft_order', id=order.id)}}">
                                <i class="fa fa-ban"></i>{% trans %}Draft Order{% endtrans %}
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
{% endblock %}

flaskshop/templates/dashboard/order/list.html
{% import 'dashboard/_vendor.html' as vendor %}
{% extends 'dashboard/layout.html' %}
{% block body %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title" style="line-height: 30px;">{% trans %}Order List{% endtrans %}</h3>
                        <div class="card-tools">
                            <form>
                            <div class="row">
                                <div class="form-group col-2">
                                <select class="form-control" name="status">
                                    <option value="" disabled selected hidden>{% trans %}Status{% endtrans %}</option>
                                    {% for stat in order_stats_kinds%}
                                    <option value="{{stat.value}}">{{stat.name}}</option>
                                    {% endfor %}
                                </select>
                                </div>
                                <div class="form-group col-3">
                                    <input type="text" name="order_number" class="float-right form-control"
                                        placeholder="{% trans %}Order No.{% endtrans %}">
                                </div>
                                <div class="form-group col-5">
                                    <input type="text" name="created_at" class="float-right form-control" 
                                        placeholder="{% trans %}Created At{% endtrans %}" id="reservation">
                                </div>
                                <div class="form-group col-2">
                                    <button type="submit" class="btn btn-default">{% trans %}Query{% endtrans %}</button>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <tr>
                                {% for th in props.values() %}
                                <th>{{th}}</th>
                                {% endfor %}
                                <th>{% trans %}Operation{% endtrans %}</th>
                            </tr>
                            {% for item in items %}
                            <tr>
                                {% for prop in props.keys() %}
                                <td>{{ item | attr(prop) }}</td>
                                {% endfor %}
                                <td>
                                    <a href="{{url_for('dashboard.order_detail', id=item.id)}}"
                                        class="btn btn-info btn-sm">{% trans %}View{% endtrans %}</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <!-- /.card-body -->
                    {% if pagination %}
                    <div class="card-footer clearfix">
                        {{vendor.render_pagination(pagination, size='sm', align='right')}}
                    </div>
                    {% endif %}
                </div>
                <!-- /.card -->
            </div>
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

{% endblock %}

{% block tail_js %}
<script src="{{ url_for('static', filename='build/dashboard/daterangepicker.js') }}"></script>
{% endblock %}