flaskshop/account/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app
from flask_login import login_required, current_user, login_user, logout_user
from flask_mail import Message
from pluggy import HookimplMarker
from flask_babel import lazy_gettext
import random
import string

from .forms import AddressForm, LoginForm, RegisterForm, ChangePasswordForm, ResetPasswd
from .models import UserAddress, User
from flaskshop.utils import flash_errors
from flaskshop.order.models import Order

impl = HookimplMarker("flaskshop")


def index():
    form = ChangePasswordForm(request.form)
    orders = Order.get_current_user_orders()
    return render_template("account/details.html", form=form, orders=orders)


def login():
    """login page."""
    form = LoginForm(request.form)
    if form.validate_on_submit():
        login_user(form.user)
        redirect_url = request.args.get("next") or url_for("public.home")
        flash(lazy_gettext("You are log in."), "success")
        return redirect(redirect_url)
    else:
        flash_errors(form)
    return render_template("account/login.html", form=form)

def id_generator(size=8, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def resetpwd():

    '''Reset user password'''
    form = ResetPasswd(request.form)

    if form.validate_on_submit():
        flash(lazy_gettext("Check your e-mail."), "success")
        user = User.query.filter_by(email=form.username.data).first()
        new_passwd =id_generator()
        body =  render_template("account/reser_passwd_mail.html", new_passwd=new_passwd)
        msg = Message(lazy_gettext("Reset Password"),
                      recipients=[form.username.data])
        msg.body = lazy_gettext('''We cannot simply send you your old password.\n 
        A unique password has been generated for you. Change the password after logging in.\n
        New Password is: %s''' % new_passwd)
        msg.html = body
        mail = current_app.extensions.get("mail")
        mail.send(msg)
        user.update(password=new_passwd)
        return redirect(url_for("account.login"))
    else:
        flash_errors(form)
    return render_template("account/login.html", form=form, reset=True)

@login_required
def logout():
    """Logout."""
    logout_user()
    flash(lazy_gettext("You are logged out."), "info")
    return redirect(url_for("public.home"))


def signup():
    """Register new user."""
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User.create(
            username=form.username.data,
            email=form.email.data.lower(),
            password=form.password.data,
            is_active=True,
        )
        login_user(user)
        flash(lazy_gettext("You are signed up."), "success")
        return redirect(url_for("public.home"))
    else:
        flash_errors(form)
    return render_template("account/signup.html", form=form)


def set_password():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        current_user.update(password=form.password.data)
        flash(lazy_gettext("You have changed password."), "success")
    else:
        flash_errors(form)
    return redirect(url_for("account.index"))


def addresses():
    """List addresses."""
    addresses = current_user.addresses
    return render_template("account/addresses.html", addresses=addresses)


def edit_address():
    """Create and edit an address."""
    form = AddressForm(request.form)
    address_id = request.args.get("id", None, type=int)
    if address_id:
        user_address = UserAddress.get_by_id(address_id)
        form = AddressForm(request.form, obj=user_address)
    if request.method == "POST" and form.validate_on_submit():
        address_data = {
            "province": form.province.data,
            "city": form.city.data,
            "district": form.district.data,
            "address": form.address.data,
            "contact_name": form.contact_name.data,
            "contact_phone": form.contact_phone.data,
            "user_id": current_user.id
        }
        if address_id:
            UserAddress.update(user_address, **address_data)
            flash(lazy_gettext("Success edit address."), "success")
        else:
            UserAddress.create(**address_data)
            flash(lazy_gettext("Success add address."), "success")
        return redirect(url_for("account.index") + "#addresses")
    else:
        flash_errors(form)
    return render_template(
        "account/address_edit.html", form=form, address_id=address_id
    )


def delete_address(id):
    user_address = UserAddress.get_by_id(id)
    if user_address in current_user.addresses:
        UserAddress.delete(user_address)
    return redirect(url_for("account.index") + "#addresses")


@impl
def flaskshop_load_blueprints(app):
    bp = Blueprint("account", __name__)
    bp.add_url_rule("/", view_func=index)
    bp.add_url_rule("/login", view_func=login, methods=["GET", "POST"])
    bp.add_url_rule("/resetpwd", view_func=resetpwd, methods=["GET", "POST"])
    bp.add_url_rule("/logout", view_func=logout)
    bp.add_url_rule("/signup", view_func=signup, methods=["GET", "POST"])
    bp.add_url_rule("/setpwd", view_func=set_password, methods=["POST"])
    bp.add_url_rule("/address", view_func=addresses)
    bp.add_url_rule("/address/edit", view_func=edit_address, methods=["GET", "POST"])
    bp.add_url_rule(
        "/address/<int:id>/delete", view_func=delete_address, methods=["POST"]
    )
    app.register_blueprint(bp, url_prefix="/account")

flaskshop/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<div class="pagination">
  <ul class="pagination">
    <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
      <a href="
          {% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
        &laquo;
      </a>
    </li>
    {% for p in pagination.iter_pages() %}
    {% if p %}
    {% if p == pagination.page %}
    <li class="active">
      <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
    </li>
    {% else %}
    <li>
      <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled"><a href="#">&hellip;</a></li>
    {% endif %}
    {% endfor %}
    <li {% if not pagination.has_next %} class="disabled" {% endif %}>
      <a href="
          {% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
        &raquo;
      </a>
    </li>
  </ul>
</div>
{% endmacro %}

{% macro menu(menu_items, horizontal=true) %}
<ul class="menu {% if horizontal %}nav mb-4 mb-md-0{% endif %}">
  {% for item in menu_items %}
  {% with children=item.children %}
  <li class="{% if horizontal %}nav-item{% endif %} {% if children %}nav-item__dropdown{% endif %} menu__item">
    <a class="{% if horizontal %}nav-link{% endif %}" href="{{ item.url }}">
      {{ item }}
    </a>
    {% if children %}
    <div class="{% if horizontal %}nav-item__dropdown-content{% else %}nav-item__submenu{% endif %}">
      <div class="container">
        <ul>
          {% for child in children %}
          <li>
            <a href="{{ child.url }}">
              {% if horizontal %}
              <strong>{{ child }}</strong>
              {% else %}
              {{ child }}
              {% endif %}
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    {% endif %}
  </li>
  {% endwith %}
  {% endfor %}
</ul>
{% endmacro %}

{% macro format_address(address) %}
{{ address.province }}-{{ address.city }}-{{ address.district }}<br>
{{ address.address }}<br>
{{ address.contact_name }}<br>
{{ address.contact_phone }}<br>
{% endmacro %}

{% macro footer_menu(menu_items) %}
{% for item in menu_items %}
{% with children=item.children %}
<div class="col-6 col-md-2">
  <ul class="menu">
    <li class="{% if children %}nav-item__dropdown{% endif %} menu__item">
      <a href="{{ item.url }}">
        {{item.title}}
      </a>
      {% if children %}
      <hr />
      <div class="nav-item__submenu">
        <ul>
          {% for child in children %}
          <li>
            <a href="{{ child.url }}">
              {{child.title}}
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}
    </li>
  </ul>
</div>
{% endwith %}
{% endfor %}
{% endmacro %}

{% macro navlink(endpoint, name, active='') %}
<li class="list-group-item {% if endpoint == request.endpoint or endpoint == active or active == True %}active{% endif %}">
    <a href="{{ url_for(endpoint) }}">{{ name }}</a>
</li>
{% endmacro %}

flaskshop/templates/adminlte.html
{% import 'admin/macros.html' as macro with context -%}

{% block head_tail %}
    <link href="{{ url_for('static', filename='admin/css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='admin/css/adminlte.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='admin/css/admin.css') }}" rel="stylesheet">
{% endblock %}


<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

{% block page_body %}
    <body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
                </li>
            </ul>


            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">

                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell-o"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fa fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fa fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fa fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i
                            class="fa fa-th-large"></i></a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="{{ url_for('admin.index') }}" class="brand-link">
                <img src="{{ url_for('static', filename='img/AdminLTELogo.png') }}" alt="AdminLTE Logo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Flask-Shop</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="{{ url_for('static', filename='img/user2-160x160.jpg') }}"
                             class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        {%- for item in admin_view.admin.menu() %}
                            {%- if item.is_category() -%}
                                {% set children = item.get_children() %}
                                {%- if children %}
                                    {% set class_name = item.get_class_name() %}
                                        {%- if item.is_active(admin_view) %}
                                            <li class="nav-item has-treeview menu-open">
                                            <a href="#" class="nav-link active">
                                                <i class="{{ item.class_name }}"></i>
                                                <p>{{ item.name }}<i class="right fa fa-angle-left"></i></p>
                                            </a>
                                        {% else %}
                                            <li class="nav-item has-treeview">
                                            <a href="#" class="nav-link">
                                                <i class="{{ item.class_name }}"></i>
                                                <p>{{ item.name }}<i class="right fa fa-angle-left"></i></p>
                                            </a>
                                        {% endif %}
                                        <ul class="nav nav-treeview">
                                            {%- for child in children -%}
                                                {% set class_name = child.get_class_name() %}
                                                <li class="nav-item">
                                                    {%- if child.is_active(admin_view) %}
                                                        <a href="{{ child.get_url() }}" class="nav-link active"
                                                                {% if child.target %}
                                                           target="{{ child.target }}"{% endif %}>
                                                    {% else %}
                                                        <a href="{{ child.get_url() }}" class="nav-link"
                                                                {% if child.target %}
                                                           target="{{ child.target }}"{% endif %}>
                                                    {%- endif %}
                                                    {{ macro.menu_icon(child) }}<p>{{ child.name }}</p></a>
                                                </li>
                                            {%- endfor %}
                                        </ul>
                                    </li>
                                {% endif %}
                            {%- else %}
                                {%- if item.is_accessible() and item.is_visible() -%}
                                    {% set class_name = item.get_class_name() %}
                                    <li class="nav-item">
                                        {%- if item.is_active(admin_view) %}
                                            <a href="{{ item.get_url() }}" class="nav-link active" {% if item.target %}
                                               target="{{ item.target }}"{% endif %}>
                                        {% else %}
                                            <a href="{{ item.get_url() }}" class="nav-link" {% if item.target %}
                                               target="{{ item.target }}"{% endif %}>
                                        {%- endif %}
                                        {{ macro.menu_icon(item) }}<p>{{ item.name }}</p></a>
                                    </li>
                                {%- endif -%}
                            {% endif -%}
                        {% endfor %}
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">{{ admin_view.name|capitalize }}</h1>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            {# store the jinja2 context for form_rules rendering logic #}
            {% set render_ctx = h.resolve_ctx() %}
            <!-- Main content -->
            {% block body %} {% endblock %}
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->


    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{{ url_for('static', filename='admin/js/jquery.min.js') }}"></script>
    {#<!-- Bootstrap 4 -->#}
    <script src="{{ url_for('static', filename='admin/js/bootstrap.bundle.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ url_for('static', filename='admin/js/adminlte.min.js') }}"></script>
    {% if admin_view.extra_js %}
        {% for js_url in admin_view.extra_js %}
            <script src="{{ js_url }}" type="text/javascript"></script>
        {% endfor %}
    {% endif %}
    {% block tail_js %} {% endblock %}
    </body>
{% endblock %}

flaskshop/templates/base.html
{% import '_macros.html' as macros %}
<!DOCTYPE html>
<html class="no-js">

  <head>
    {% if config.GA_MEASUREMENT_ID %}
      <script async src="https://www.googletagmanager.com/gtag/js?id={{ config.GA_MEASUREMENT_ID }}"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', '{{ config.GA_MEASUREMENT_ID }}');
      </script>
    {% endif %}
    <title>{% block title %}{% trans %}flask store{% endtrans %}{% endblock %}</title>
    {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Saleor">
    <meta name="theme-color" content="#333333">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="og:type" content="website">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {% endblock meta %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='build/storefront.css') }}">
    {% block stylesheet %}{% endblock stylesheet %}
  </head>

  <body>
    {% block header %}
    <header class="navbar" role="navigation">
      <div class="navbar__login container-fluid">
        <div class=" d-none d-md-block container">
          <div class="row">
            <div class="col-6">
              <p class="text-left">{{ settings['project_title'].value }} - {{ settings['project_subtitle'].value }}</p>
            </div>
            <div class="col-6">
              <ul class="float-right">
                {% if current_user.is_authenticated %}
                {% if current_user.can_edit() %}

                <li>
                  <a href="{{ url_for('dashboard.index') }}" target="_blank" rel="noopener">
                    {% trans %}Dashboard{% endtrans %}
                  </a>
                </li>
                {% endif %}
                {{ run_hook("flaskbb_tpl_user_nav_loggedin_before") }}
                <li>
                  <a href="{{ url_for('account.index') }}">
                    {% trans %}Your Account{% endtrans %}</a>
                </li>

                <li>
                  <a href="{{ url_for('account.logout') }}">
                    {% trans %}Log Out{% endtrans %}</a>
                </li>

                {% else %}
                <li>
                  <a rel="nofollow" href="{{ url_for('account.signup') }}">
                    {% trans %}Register{% endtrans %}
                  </a>
                </li>
                <li>
                  <a rel="nofollow" href="{{ url_for('account.login') }}">
                    {% trans %}Log in{% endtrans %}
                  </a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar__brand container-fluid d-block">
        <div class="container">
          <div class="row no-gutters" style="width:100%">
            <div class="col-8 col-md-4 navbar__logo">
              <div class="menu-icon-mobile d-md-none navbar__brand__menu-toggle closed open">
                <svg data-src="{{ url_for('static', filename='img/mobile-menu.svg') }}" width="28px"
                  height="20px"></svg>
              </div>
              <a href="{{ url_for('public.home') }}">
                <svg data-src="{{ url_for('static', filename='img/logo-document.svg') }}" width="176px"
                  height="38px"></svg>
              </a>
            </div>
            <div class="col-2 col-md-5 navbar__search static">
              {% if current_app.config['USE_ES']  %}
              <div class="d-md-none mobile-search-icon">
                <svg data-src="{{ url_for('static', filename='img/search.svg') }}" width="30" height="30"></svg>
              </div>
              <form class="form-inline search-form" action="/search">
                <div class="mobile-close-search d-md-none">
                  <svg data-src="{{ url_for('static', filename='img/close.svg') }}" width="30" height="30"></svg>
                </div>
                <input class="form-control" type="text" name="q" value="{{request.args.get('q', '')}}"
                  placeholder="Search for product" required>
                <button class="btn btn-primary" type="submit" style="padding-top: 0px;padding-bottom: 0px">
                  Search<svg data-src="{{ url_for('static', filename='img/search.svg') }}" width="18" height="18"></svg>
                </button>
              </form>
              {% endif %}
            </div>
            <div class="col-2 col-md-3">
              <div class="navbar__brand__cart float-right">
                <a rel="nofollow" class="cart__icon" href="{{ url_for('checkout.cart_index') }}">
                  <span class="cart-label d-none d-md-inline-block">
                    {% trans %}Your Cart{% endtrans %}
                  </span>
                  <div class="navbar__brand__cart__icon">
                    <svg data-src="{{ url_for('static', filename='img/cart.svg') }}" width="24" height="24"></svg>
                  </div>
                  {% if current_user.is_authenticated and current_user_cart.quantity %}
                  <span class="badge ">
                    {{ current_user_cart.quantity }}
                  </span>
                  {% else %}
                  <span class="badge empty">
                    0
                  </span>
                  {% endif %}
                </a>
                <div class="cart-dropdown d-none">
                  {% include "public/cart_dropdown.html" %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% block navigation %}
      <div class="navbar__menu container d-block">
        <nav class="navigation">
          {{ macros.menu(top_menu) }}
        </nav>
      </div>
      {% endblock %}
    </header>
    {% endblock %}
    <div class="container maincontent">
      {% block topcontent %}{% endblock topcontent %}

      {% for message in get_flashed_messages(with_categories=True) %}
      <br>
      <div class="alert alert-{{ message[0] }}">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message[1] }}
      </div>
      {% endfor %}

      {% block breadcrumb %}
      {% endblock breadcrumb %}
      {% block content %}
      {% endblock content %}
    </div>
    {% block footer %}
    <footer class="footer">
      <div class="footer__menus">
        <div class="container">
          <div class="row">
            {{ macros.footer_menu(bottom_menu) }}
            <div class="col-md-2 col-6">
              <ul class="menu">
                <li class="nav-item__dropdown menu__item">
                  <a>
                    <strong>
                      {% trans %}Account{% endtrans %}
                    </strong>
                  </a>
                  <hr />
                <li>
                  <a rel="nofollow" href="{{ url_for('checkout.cart_index') }}">
                    {% trans %}Your Cart{% endtrans %}
                  </a>
                </li>
                {% if current_user.is_authenticated %}
                {% if current_user.can_edit() %}
                <li>
                  <a href="{{ url_for('dashboard.index') }}" target="_blank" rel="noopener">
                    {% trans %}Dashboard{% endtrans %}
                  </a>
                </li>
                {% endif %}
                <li>
                  <a href="{{ url_for('account.index') }}">
                    {% trans %}Your account{% endtrans %}
                  </a>
                </li>

                <li>
                  <a href="{{ url_for('account.logout') }}">
                    {% trans %}Log out{% endtrans %}</a>
                </li>

                {% else %}
                <li>
                  <a rel="nofollow" href="{{ url_for('account.signup') }}">
                    {% trans %}Register{% endtrans %}
                  </a>
                </li>
                <li>
                  <a rel="nofollow" href="{{ url_for('account.login') }}">
                    {% trans %}Log in{% endtrans %}
                  </a>
                </li>
                {% endif %}
              </ul>
            </div>
            <div class="offset-md-2 col-md-4 col-12">
              <div class="footer__menus__social-container">
                <div class="footer__menus__social">
                  <a target="_blank" rel="noopener" class="social-footer" href="https://www.facebook.com/mirumeelabs/">
                    <svg data-src="{{ url_for('static', filename='img/facebook-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://github.com/mirumee/saleor">
                    <svg data-src="{{ url_for('static', filename='img/github-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://twitter.com/getsaleor">
                    <svg data-src="{{ url_for('static', filename='img/twitter-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://plus.google.com/+Mirumee">
                    <svg data-src="{{ url_for('static', filename='img/google-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://www.meetup.com/Mirumee-Talks/">
                    <svg data-src="{{ url_for('static', filename='img/meetup-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer"
                    href="https://linkedin.com/company/mirumee-software">
                    <svg data-src="{{ url_for('static', filename='img/linkedin-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer" href="https://dribbble.com/mirumee">
                    <svg data-src="{{ url_for('static', filename='img/dribbble-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                  <a target="_blank" rel="noopener" class="social-footer"
                    href="https://www.instagram.com/explore/tags/mirumee/">
                    <svg data-src="{{ url_for('static', filename='img/instagram-logo.svg') }}" width="45px"
                      height="45px" />
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="footer__copy">
        <div class="container">
          <div class="row">
            <div class="col-4">
              <a href="{{ url_for('public.home') }}" class="footer__logo float-md-left">
                <svg data-src="{{ url_for('static', filename='img/logo-document.svg') }}" width='176px' height='38px' />
              </a>
            </div>
            <div class="col-8 footer__copy-text">{{ settings['project_copyright'].value }}</div>
          </div>
        </div>
      </div>
    </footer>
    {% endblock %}
    {% block footer_scripts %}
      <script src="{{ url_for('static', filename='build/storefront.js') }}"></script>
    {% endblock footer_scripts %}
  </body>

</html>

flaskshop/templates/no_nav_base.html
{% extends "base.html" %}

{% block navigation %}

{% endblock %}