flaskshop/dashboard/__init__.py
from . import views
#TODO: mail_send, mail_compose, change_user_right,

flaskshop/dashboard/views.py
from functools import wraps
from flask import Blueprint, render_template, abort, redirect, url_for
from flask_login import login_required, current_user

from flaskshop.account.models import User, UserAddress
from flaskshop.public.models import MenuItem

from .models import DashboardMenu
from .forms import DashboardMenuForm

blueprint = Blueprint("dashboard", __name__, url_prefix="/dashboard")


@blueprint.context_processor
def inject_param():
    menus = DashboardMenu.first_level_items()
    return {"menus": menus}


def admin_required(func):
    @wraps(func)
    def decorated_view(*args, **kwargs):
        if not current_user.is_admin:
            abort(401)
        return func(*args, **kwargs)

    return decorated_view


@blueprint.before_request
@admin_required
@login_required
def before_request():
    """The whole blueprint need to login first"""
    pass


@blueprint.route("/")
def index():
    return render_template("dashboard/index.html")


@blueprint.route("/list")
def list():
    return render_template("dashboard/list.html")


@blueprint.route("/users")
def users():
    users = User.query.all()
    props = {
        "id": "ID",
        "username": "Username",
        "email": "Email",
        "active": "Is Active",
        "is_admin": "Is Admin",
    }
    context = {}
    return render_template("dashboard/list.html", props=props, items=users)


@blueprint.route("/menus")
def menus():
    menus = MenuItem.query.all()
    props = {
        "id": "ID",
        "title": "Title",
        "order": "Order",
        "site_id": "Site Id",
        "parent_id": "Parent Id",
    }
    context = {
        "title": "Site Menus",
        "create_endpoint": "dashboard.dashboard_menus_create",
        "edit_endpoint": "dashboard.dashboard_menus_edit",
        "items": menus,
        "props": props,
    }
    return render_template("dashboard/list.html", **context)


@blueprint.route("/dashboard_menus")
def dashboard_menus():
    dashboard_menus = DashboardMenu.query.all()
    props = {
        "id": "ID",
        "title": "Title",
        "order": "Order",
        "endpoint": "Endpoint",
        "icon_cls": "Icon class",
        "parent_id": "Parent Id",
    }
    context = {
        "title": "Dashboard Menus",
        "create_endpoint": "dashboard.dashboard_menus_create",
        "edit_endpoint": "dashboard.dashboard_menus_edit",
        "items": dashboard_menus,
        "props": props,
    }
    return render_template("dashboard/list.html", **context)


@blueprint.route("/dashboard_menus/create", methods=["GET", "POST"])
def dashboard_menus_create():
    form = DashboardMenuForm()
    if form.validate_on_submit():
        menu = DashboardMenu()
        form.populate_obj(menu)
        menu.save()
        return redirect(url_for("dashboard.dashboard_menus"))
    parents = DashboardMenu.first_level_items()
    return render_template("dashboard/dashboard_menu.html", form=form, parents=parents)


@blueprint.route("/dashboard_menus/<menu_id>/edit", methods=["GET", "POST"])
def dashboard_menus_edit(menu_id):
    menu = DashboardMenu.get_by_id(menu_id)
    form = DashboardMenuForm(obj=menu)
    if form.validate_on_submit():
        form.populate_obj(menu)
        menu.save()
        return redirect(url_for("dashboard.dashboard_menus"))
    parents = DashboardMenu.first_level_items()
    return render_template("dashboard/dashboard_menu.html", form=form, parents=parents)

flaskshop/dashboard/views/__init__.py
from . import bp

flaskshop/dashboard/views/mail.py
from flask import render_template, redirect, url_for, request
from sqlalchemy import or_
from flask_babel import lazy_gettext

def mails():
    page = request.args.get("page", type=int, default=1)
    search_word = request.args.get("keyword")

flaskshop/dashboard/views/order.py
from datetime import datetime
from flask import request, render_template
from flask_babel import lazy_gettext

from flaskshop.order.models import Order
from flaskshop.constant import OrderStatusKinds


def orders():
    page = request.args.get("page", type=int, default=1)
    query = Order.query.order_by(Order.id.desc())

    status = request.args.get("status", type=int)
    if status:
        query = query.filter_by(status=status)
    order_no = request.args.get("order_number", type=str)
    if order_no:
        query = query.filter(Order.token.like(f"%{order_no}%"))
    created_at = request.args.get("created_at", type=str)
    if created_at:
        start_date, end_date = created_at.split("-")
        start_date = datetime.strptime(start_date.strip(), "%m/%d/%Y")
        end_date = datetime.strptime(end_date.strip(), "%m/%d/%Y")
        query = query.filter(Order.created_at.between(start_date, end_date))
    pagination = query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "identity": lazy_gettext("Identity"),
        "status_human": lazy_gettext("Status"),
        "total_human": lazy_gettext("Total"),
        "user": lazy_gettext("User"),
        "created_at": lazy_gettext("Created At"),
    }
    context = {
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "order_stats_kinds": OrderStatusKinds,
    }
    return render_template("order/list.html", **context)


def order_detail(id):
    order = Order.get_by_id(id)
    return render_template("order/detail.html", order=order)


def send_order(id):
    order = Order.get_by_id(id)
    order.delivered()
    return render_template("order/detail.html", order=order)


def draft_order(id):
    order = Order.get_by_id(id)
    order.draft()
    return render_template("order/detail.html", order=order)

flaskshop/dashboard/views/product.py
from datetime import datetime

from flask import request, render_template, redirect, url_for, current_app
from flask_babel import lazy_gettext
from flaskshop.product.models import (
    ProductAttribute,
    ProductType,
    Collection,
    Product,
    Category,
    ProductType,
    ProductVariant,
)
from flaskshop.dashboard.forms import (
    AttributeForm,
    CollectionForm,
    CategoryForm,
    ProductTypeForm,
    ProductForm,
    ProductCreateForm,
    VariantForm,
)


def attributes():
    page = request.args.get("page", type=int, default=1)
    pagination = ProductAttribute.query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "values_label": lazy_gettext("Value"),
        "types_label": lazy_gettext("ProductType"),
    }
    context = {
        "title": lazy_gettext("Product Attribute"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": gettext("attributes"),
    }
    return render_template("list.html", **context)


def attributes_manage(id=None):
    if id:
        attr = ProductAttribute.get_by_id(id)
        form = AttributeForm(obj=attr)
    else:
        form = AttributeForm()
    if form.validate_on_submit():
        if not id:
            attr = ProductAttribute()
        attr.title = form.title.data
        attr.update_types(form.types.data)
        attr.update_values(form.values.data)
        attr.save()
        return redirect(url_for("dashboard.attributes"))
    product_types = ProductType.query.all()
    return render_template(
        "product/attribute.html", form=form, product_types=product_types
    )


def collections():
    page = request.args.get("page", type=int, default=1)
    pagination = Collection.query.paginate(page, 10)
    props = {"id": lazy_gettext("ID"), "title": lazy_gettext("Title"), "created_at": lazy_gettext("Created At")}
    context = {
        "title": lazy_gettext("Product Collection"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": gettext("collections"),
    }
    return render_template("list.html", **context)


def collections_manage(id=None):
    if id:
        collection = Collection.get_by_id(id)
        form = CollectionForm(obj=collection)
    else:
        form = CollectionForm()
    if form.validate_on_submit():
        if not id:
            collection = Collection()
        collection.title = form.title.data
        collection.update_products(form.products.data)
        image = form.bgimg_file.data
        if image:
            background_img = image.filename
            upload_file = current_app.config["UPLOAD_DIR"] / background_img
            upload_file.write_bytes(image.read())
            collection.background_img = (
                current_app.config["UPLOAD_FOLDER"] + "/" + background_img
            )
        collection.save()
        return redirect(url_for("dashboard.collections"))
    products = Product.query.all()
    return render_template("product/collection.html", form=form, products=products)


def categories():
    page = request.args.get("page", type=int, default=1)
    pagination = Category.query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "parent": lazy_gettext("Parent"),
        "created_at": lazy_gettext("Created At"),
    }
    context = {
        "title": lazy_gettext("Product Category"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": gettext("categories"),
    }
    return render_template("list.html", **context)


def categories_manage(id=None):
    if id:
        category = Category.get_by_id(id)
        form = CategoryForm(obj=category)
    else:
        form = CategoryForm()
    if form.validate_on_submit():
        if not id:
            category = Category()
        category.title = form.title.data
        category.parent_id = form.parent_id.data
        image = form.bgimg_file.data
        if image:
            background_img = image.filename
            upload_file = current_app.config["UPLOAD_DIR"] / background_img
            upload_file.write_bytes(image.read())
            category.background_img = (
                current_app.config["UPLOAD_FOLDER"] + "/" + background_img
            )
        category.save()
        return redirect(url_for("dashboard.categories"))
    parents = Category.first_level_items()
    return render_template("product/category.html", form=form, parents=parents)


def product_types():
    page = request.args.get("page", type=int, default=1)
    pagination = ProductType.query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "has_variants": lazy_gettext("Has Variants"),
        "is_shipping_required": lazy_gettext("Is Shipping Required"),
        "created_at": lazy_gettext("Created At"),
    }
    context = {
        "title": lazy_gettext("Product Type"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": gettext("product_types"),
    }
    return render_template("list.html", **context)


def product_types_manage(id=None):
    if id:
        product_type = ProductType.get_by_id(id)
        form = ProductTypeForm(obj=product_type)
    else:
        form = ProductTypeForm()
    if form.validate_on_submit():
        if not id:
            product_type = ProductType()
        product_type.update_product_attr(form.product_attributes.data)
        product_type.update_variant_attr(form.variant_attr_id.data)
        del form.product_attributes
        del form.variant_attr_id
        form.populate_obj(product_type)
        product_type.save()
        return redirect(url_for("dashboard.product_types"))
    attributes = ProductAttribute.query.all()
    return render_template(
        "product/product_type.html", form=form, attributes=attributes
    )


def products():
    page = request.args.get("page", type=int, default=1)
    query = Product.query

    on_sale = request.args.get("sale", type=int)
    if on_sale is not None:
        query = query.filter_by(on_sale=on_sale)
    category = request.args.get("category", type=int)
    if category:
        query = query.filter_by(category_id=category)
    title = request.args.get("title", type=str)
    if title:
        query = query.filter(Product.title.like(f"%{title}%"))
    created_at = request.args.get("created_at", type=str)
    if created_at:
        start_date, end_date = created_at.split("-")
        start_date = datetime.strptime(start_date.strip(), "%m/%d/%Y")
        end_date = datetime.strptime(end_date.strip(), "%m/%d/%Y")
        query = query.filter(Product.created_at.between(start_date, end_date))

    pagination = query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "on_sale_human": lazy_gettext("On Sale"),
        "sold_count": lazy_gettext("Sold Count"),
        "price_human": lazy_gettext("Price"),
        "category": lazy_gettext("Category"),
    }
    context = {
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "categories": Category.query.all(),
    }
    return render_template("product/list.html", **context)


def product_detail(id):
    product = Product.get_by_id(id)
    return render_template("product/detail.html", product=product)


def _save_product(product, form):
    product.update_images(form.images.data)
    product.update_attributes(form.attributes.data)
    del form.images
    del form.attributes
    form.populate_obj(product)
    product.save()
    return product


def product_edit(id):
    product = Product.get_by_id(id)
    form = ProductForm(obj=product)
    if form.validate_on_submit():
        _save_product(product, form)
        return redirect(url_for("dashboard.product_detail", id=product.id))
    categories = Category.query.all()
    context = {"form": form, "categories": categories, "product": product}
    return render_template("product/product_edit.html", **context)


def product_create_step1():
    form = ProductCreateForm()
    if form.validate_on_submit():
        return redirect(
            url_for(
                "dashboard.product_create_step2",
                product_type_id=form.product_type_id.data,
            )
        )
    product_types = ProductType.query.all()
    return render_template(
        "product/product_create_step1.html", form=form, product_types=product_types
    )


def product_create_step2():
    form = ProductForm()
    product_type_id = request.args.get("product_type_id", 1, int)
    product_type = ProductType.get_by_id(product_type_id)
    categories = Category.query.all()
    if form.validate_on_submit():
        product = Product(product_type_id=product_type_id)
        product = _save_product(product, form)
        #product.generate_variants()
        return redirect(url_for("dashboard.product_detail", id=product.id))
    return render_template(
        "product/product_create_step2.html",
        form=form,
        product_type=product_type,
        categories=categories,
    )


def variant_manage(id=None):
    if id:
        variant = ProductVariant.get_by_id(id)
        form = VariantForm(obj=variant)
    else:
        form = VariantForm()
    if form.validate_on_submit():
        if not id:
            variant = ProductVariant()
        form.populate_obj(variant)
        product_id = request.args.get("product_id")
        if product_id:
            variant.product_id = product_id
        variant.sku = str(variant.product_id) + "-" + str(form.sku_id.data)
        variant.save()
        return redirect(url_for("dashboard.product_detail", id=variant.product_id))
    return render_template("product/variant.html", form=form)

flaskshop/templates/dashboard/index.html
{% extends 'dashboard/layout.html' %}
{% block body %}
<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <div class="col-md-8">

                <div class="row">
                    <div class="col-md-6">
                        <div class="info-box mb-3">
                            <span class="info-box-icon bg-success elevation-1"><i
                                    class="fa fa-shopping-cart"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text">{% trans %}Sales{% endtrans %}</span>
                                <span class="info-box-text"><b>{{orders_today}}</b> {% trans %}today and{% endtrans %} <b>{{orders_total}}</b>
                                    {% trans %}total{% endtrans %}</span>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="info-box mb-3">
                            <span class="info-box-icon bg-warning elevation-1"><i class="fa fa-users"></i></span>
                            <div class="info-box-content">
                                <span class="info-box-text">{% trans %}Members{% endtrans %}</span>
                                <span class="info-box-text"><b>{{users_today}}</b> {% trans %}new in{% endtrans %} <b>{{users_total}}</b>
                                    {% trans %}accounts{% endtrans %}</span>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
                <div class="card">
                    <div class="card-body p-0">
                        <ul class="navi-card">
                            <li class="item">
                                <a href="{{url_for('dashboard.orders', status=order_fulfill.kind)}}">
                                    <span>{{order_fulfill.count}} {% trans %}Orders are ready to fulfill{% endtrans %}</span>
                                    <span class="right">></span>
                                </a>
                            </li>
                            <li class="item">
                                <a href="{{url_for('dashboard.orders', status=order_unfulfill.kind)}}">
                                    <span>{{order_unfulfill.count}} {% trans %}Payments to capture{% endtrans %}</span>
                                    <span class="right">></span>
                                </a>
                            </li>
                            <li class="item">
                                <a href="{{url_for('dashboard.products', sale=True)}}">
                                    <span>{{onsale_products_count}} {% trans %}products is on sale{% endtrans %}</span>
                                    <span class="right">></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{% trans %}Top Products{% endtrans %}</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <ul class="products-list product-list-in-card pl-2 pr-2">
                            {% for product in top_products %}
                            <li class="item">
                                <div class="product-img">
                                    <img src="{{ product.first_img }}"
                                        alt="Product Image" class="img-size-50">
                                </div>
                                <div class="product-info">
                                    <a href="{{url_for('dashboard.product_detail', id=product.id)}}" class="product-title">{{product.title}}
                                        <span class="badge badge-info float-right">{{product.price_human}}</span></a>
                                    <span class="product-description">
                                        {{product.description}}
                                    </span>
                                    <span class="product-description">
                                        {{product.order_count}} {% trans %}Ordered{% endtrans %}
                                    </span>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->

            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{% trans %}Activity{% endtrans %}</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <ul class="activity product-list-in-card pl-2 pr-2">
                            {% for a in activity %}
                            <li class="item">
                                <span class="activity-title">{% trans %}Order{% endtrans %} #{{a.order_id}} {% trans %}was{% endtrans %} {{order_events(a.type_).name}}</span>
                                <span>{{a.created_at_human}}</span>
                            </li>
                            {% else %}
                            <li class="item">
                                <span class="activity-title">{% trans %}There is no recent activity{% endtrans %} </span>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!--/. container-fluid -->
</section>
{% endblock %}

flaskshop/templates/dashboard/layout.html
{% block head_tail %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='build/dashboard/layout.css') }}">
{% endblock %}


<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

{% block page_body %}

<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{{url_for('dashboard.index')}}" class="nav-link">{% trans %}Dashboard{% endtrans %}</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{{url_for('public.home')}}" class="nav-link" target="_blank">{% trans %}Front Site{% endtrans %}</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                        <i class="fa fa-th-large"></i>
                    </a>
                </li>
            </ul>

        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="{{ url_for('dashboard.index') }}" class="brand-link">
                <img src="{{ url_for('static', filename='img/logo.svg') }}"
                    class="brand-image" >
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="{{ current_user.avatar }}" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">{{current_user.username}}</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        {%- for item in menus %}
                        <li class="nav-item has-treeview {% if item.is_active() %}menu-open{% endif %}">
                            <a href="{{item.get_url()}}" class="nav-link {%- if item.is_active() %} active{% endif %}">
                                <i class="fa nav-icon {{ item.icon_cls }}"></i>
                                <p>{{ item.title }}
                                    {%- if item.children %}<i class="right fa fa-angle-left"></i>{% endif %}
                                </p>
                            </a>
                            {%- if item.children %}
                            <ul class="nav nav-treeview">
                                {%- for child in item.children -%}
                                <li class="nav-item">
                                    <a href="{{ child.get_url() }}"
                                        class="nav-link {%- if child.is_active() %} active{%- endif %}">
                                        <i class="fa fa-circle-o nav-icon"></i>
                                        <p>{{ child.title }}</p>
                                    </a>
                                </li>
                                {%- endfor %}
                            </ul>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                </nav>
            </div>
        </aside>

        <div class="content-wrapper">
            <section class="content-header">
                <div class="container-fluid">
                </div>
            </section>
            <section class="content">
            {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message[1] }}
            </div>
            {% endfor %}
        </section>
            {% block body %} {% endblock %}
        </div>
        <aside class="control-sidebar control-sidebar-dark">
        </aside>
    </div>
    <script src="{{ url_for('static', filename='build/dashboard/layout.js') }}"></script>
    {% block tail_js %} {% endblock %}
</body>
{% endblock %}

flaskshop/templates/dashboard/list.html
{% import 'dashboard/_vendor.html' as vendor %}
{% extends 'dashboard/layout.html' %}
{% block body %}
<section class="content">
    <div class="container-fluid">

        <!-- /.row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{{title}}</h3>

                        <div class="card-tools" style="display: flex;">
                            <div class="input-group input-group-sm">
                                <input type="text" name="table_search" class="form-control float-right"
                                    placeholder="Search">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                            <div class="input-group input-group-sm" style="width:auto;margin-left: 10px;">
                                <a href="{{url_for('dashboard.{}_manage'.format(identity))}}"
                                    class="btn btn-success btn-sm">{% trans %}Create{% endtrans %}</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <tr>
                                {% for th in props.values() %}
                                <th>{{th}}</th>
                                {% endfor %}
                                <th>{% trans %}Operation{% endtrans %}</th>
                            </tr>
                            {% for item in items %}
                            <tr>
                                {% for prop in props.keys() %}
                                <td>{{ item | attr(prop) }}</td>
                                {% endfor %}
                                <td>
                                    <a href="{{url_for('dashboard.{}_manage'.format(identity), id=item.id)}}"
                                        class="btn btn-primary btn-sm">{% trans %}Edit{% endtrans %}</a>
                                    <a data-url="{{identity}}/{{item.id}}/delete"
                                        class="btn btn-danger btn-sm delete-btn">{% trans %}Delete{% endtrans %}</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <!-- /.card-body -->
                    {% if pagination %}
                    <div class="card-footer clearfix">
                        {{vendor.render_pagination(pagination, size='sm', align='right')}}
                    </div>
                    {% endif %}
                </div>
                <!-- /.card -->
            </div>
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

{% endblock %}

{% block tail_js %}
<script src="{{ url_for('static', filename='build/dashboard/list.js') }}"></script>
{% endblock %}